[tool.poetry]
name = "chip8"
version = "0.1.0"
description = ""
authors = ["Kyle Bernstein <kbernst30@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
